### ISSUE TITLE
src/App.js Line 26:22: 'getData' is defined but never used no-unused-vars

### ISSUE THREAD

**Issue by IronWill79** [moeabraham/proj3#1]
https://github.com/moeabraham/proj3/blob/95109a5fa0790851feee607442eb14e701c18ea5/src/App.js#L26

Is this where the above error is occuring?

**Comment by moeabraham** [comment]
yeah most probably, I am not sure why is it not working ? I only have one
fetch method

**Comment by IronWill79** [comment]
Can't test in my current environment, but I will when I can. I'll get back to you :)

**Comment by moeabraham** [comment]
Ok thanks a lot

**Comment by IronWill79** [comment]
Not sure how you were getting this error with the existing code. I never got that error. I got a CORS error. This is actually a change required on the backend. You have the call to `app.use(cors());` too low in the app.js file. It needs to be above any of the routes to be effective. Move `app.use(cors());` from below `app.use('/', musicRouter);` to above `app.use(logger('dev'));`.

**Comment by moeabraham** [comment]
Hey Will, just saw your message, can't thank you enough man, that actually
did work. while we at it I am trying to create a music app to show data, do
you happen to have any free music data API available ?
and thanks again

**Comment by IronWill79** [comment]
I don't know of any free APIs but take a look at TheMusicDB. Some of it is free. Also Spotify could be an option. You'll need to look at the terms of service. I'm not good with that legal language. Good luck.

**Comment by moeabraham** [comment]
Thanks man, I tried spitify api with the same code but it was kinda
complicated with the authorization and all

**Comment by moeabraham** [comment]
Hey I am terribly sorry for asking you to do that, but if you have time do
you mind taking another look at my repo, I am getting this SyntaxError:
Unexpected end of JSON input, at least if you can give me pointers to where
to look
